@echo off
echo Compiling whoami.cpp...
g++ -O3 -o ../cmds/whoami.exe whoami.cpp
echo Compiling ps.cpp...
g++ -O3 -o ../cmds/ps.exe ps.cpp -lpsapi
echo Compiling kill.cpp...
g++ -O3 -o ../cmds/kill.exe kill.cpp -lpsapi
echo Compiling top.cpp...
g++ -O3 -o ../cmds/top.exe top.cpp -lpsapi
echo Compiling date.cpp...
g++ -O3 -o ../cmds/date.exe date.cpp
echo Compiling cal.cpp...
g++ -O3 -o ../cmds/cal.exe cal.cpp
echo Compiling uname.cpp...
g++ -O3 -o ../cmds/uname.exe uname.cpp
echo Compiling hostname.cpp...
g++ -O3 -o ../cmds/hostname.exe hostname.cpp
echo Compiling uptime.cpp...
g++ -O3 -o ../cmds/uptime.exe uptime.cpp
echo Compiling free.cpp...
g++ -O3 -o ../cmds/free.exe free.cpp
echo Compiling df.cpp...
g++ -O3 -o ../cmds/df.exe df.cpp
echo Compiling mount.cpp...
g++ -O3 -o ../cmds/mount.exe mount.cpp
echo Compiling umount.cpp...
g++ -O3 -o ../cmds/umount.exe umount.cpp
echo Compiling sleep.cpp...
g++ -O3 -o ../cmds/sleep.exe sleep.cpp
echo Compiling printf.cpp...
g++ -O3 -o ../cmds/printf.exe printf.cpp
echo Compiling seq.cpp...
g++ -O3 -o ../cmds/seq.exe seq.cpp
echo Compiling yes.cpp...
g++ -O3 -o ../cmds/yes.exe yes.cpp
echo Compiling ip.cpp...
g++ -O3 -o ../cmds/ip.exe ip.cpp -liphlpapi -lws2_32

echo All Batch 3 commands compiled!
