@echo off
echo Compiling head.cpp...
g++ -std=c++17 -static -o ..\cmds\head.exe head.cpp
echo Compiling tail.cpp...
g++ -std=c++17 -static -o ..\cmds\tail.exe tail.cpp
echo Compiling wc.cpp...
g++ -std=c++17 -static -o ..\cmds\wc.exe wc.cpp
echo Compiling sort.cpp...
g++ -std=c++17 -static -o ..\cmds\sort.exe sort.cpp
echo Compiling uniq.cpp...
g++ -std=c++17 -static -o ..\cmds\uniq.exe uniq.cpp
echo Compiling cut.cpp...
g++ -std=c++17 -static -o ..\cmds\cut.exe cut.cpp
echo Compiling tr.cpp...
g++ -std=c++17 -static -o ..\cmds\tr.exe tr.cpp
echo Compiling sed.cpp...
g++ -std=c++17 -static -o ..\cmds\sed.exe sed.cpp
echo Compiling awk.cpp...
g++ -std=c++17 -static -o ..\cmds\awk.exe awk.cpp
echo Compiling diff.cpp...
g++ -std=c++17 -static -o ..\cmds\diff.exe diff.cpp
echo Compiling tee.cpp...
g++ -std=c++17 -static -o ..\cmds\tee.exe tee.cpp
echo Compiling xargs.cpp...
g++ -std=c++17 -static -o ..\cmds\xargs.exe xargs.cpp
echo Compiling rev.cpp...
g++ -std=c++17 -static -o ..\cmds\rev.exe rev.cpp
echo All Batch 2 commands compiled successfully!
